# Install docker engine
# https://docs.docker.com/engine/install/ubuntu/

- name: install Docker prerequisites
  ansible.builtin.apt:
    name:
      - curl
      - gnupg
      - ca-certificates
    state: present
  become: yes

- name: load Docker gpg key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add Docker apt repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: install docker
  ansible.builtin.apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: give me docker without sudo
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
